<a href="https://colab.research.google.com/github/NatGN/Practicas-de-seminario-de-mineria-de-datos/blob/main/TEOREMA_DE_BAYES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [1]:
import pandas as pd

data = {
    'correo': [
    "gana dinero rapido",
    "oferta exclusiva gratis",
    "reunion manana",
    "adjunto el reporte",
    "gana premio grstis"
    ],

    'clase': [
        "spam",
        "spam",
        "no spam",
        "no spam",
        "spam"
    ]
}

df = pd.DataFrame(data)
print(df)

                    correo    clase
0       gana dinero rapido     spam
1  oferta exclusiva gratis     spam
2           reunion manana  no spam
3       adjunto el reporte  no spam
4       gana premio grstis     spam


In [3]:
#Convertir el texto en una matriz de caracteristicas
vectorizador = CountVectorizer()
X = vectorizador.fit_transform(df['correo'])
print(X.toarray())


[[0 1 0 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 1 0 0 0]]


In [4]:
#Establever la variable objetivo
y = df['clase']

#Entrenar el modelo de Naive Bayes
modelo = MultinomialNB()
modelo.fit(X, y)

#Ver el vocabulario que detecto el modelo
palabras = vectorizador.get_feature_names_out()
print(palabras)

tabla_prob = pd.DataFrame(
    modelo.feature_log_prob_,
    columns=palabras,
    index=modelo.classes_
)

tabla_prob.loc["spam"].sort_values(ascending=False)
print(tabla_prob)

#Predecir la clase de un nuevo correo
nuevo_correo = ["oferta gratis"]
correo_vectorizado = vectorizador.transform(nuevo_correo)
prediccion = modelo.predict(correo_vectorizado)
print(prediccion)

['adjunto' 'dinero' 'el' 'exclusiva' 'gana' 'gratis' 'grstis' 'manana'
 'oferta' 'premio' 'rapido' 'reporte' 'reunion']
          adjunto    dinero        el  exclusiva      gana    gratis  \
no spam -2.197225 -2.890372 -2.197225  -2.890372 -2.890372 -2.890372   
spam    -3.091042 -2.397895 -3.091042  -2.397895 -1.992430 -2.397895   

           grstis    manana    oferta    premio    rapido   reporte   reunion  
no spam -2.890372 -2.197225 -2.890372 -2.890372 -2.890372 -2.197225 -2.197225  
spam    -2.397895 -3.091042 -2.397895 -2.397895 -2.397895 -3.091042 -3.091042  
['spam']
