<a href="https://colab.research.google.com/github/NatGN/Practicas-de-seminario-de-mineria-de-datos/blob/main/TEOREMA_DE_BAYESEjer1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [2]:
data = {
    'reseña': [
    "el producto funciona excelente",
    "muy buena calidad",
    "el producto llego dañado",
    "muy mala calidad",
    "excelente producto y calidad"
    ],

    'clase': [
        "satisfecho",
        "satisfecho",
        "no satisfecho",
        "no satisfecho",
        "satisfecho"
    ]
}

df = pd.DataFrame(data)
print(df)

                           reseña          clase
0  el producto funciona excelente     satisfecho
1               muy buena calidad     satisfecho
2        el producto llego dañado  no satisfecho
3                muy mala calidad  no satisfecho
4    excelente producto y calidad     satisfecho


In [3]:
#Convertir el texto en una matriz de caracteristicas
vectorizador = CountVectorizer()
X = vectorizador.fit_transform(df['reseña'])
print(X.toarray())

[[0 0 0 1 1 1 0 0 0 1]
 [1 1 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1 1 0]
 [0 1 0 0 1 0 0 0 0 1]]


In [4]:
#Establever la variable objetivo
y = df['clase']

#Entrenar el modelo de Naive Bayes
modelo = MultinomialNB()
modelo.fit(X, y)

#Predecir la clase de un nuevo correo
nuevo_correo = ["el producto llego dañado"]
correo_vectorizado = vectorizador.transform(nuevo_correo)
prediccion = modelo.predict(correo_vectorizado)
print(prediccion)


['no satisfecho']
